config/routes.rb
Rails.application.routes.draw do

  resource :wechat, only: [:show, :create]
  resource :wechat, only: [:show, :create]
  resource :weixin do
    collection do
      get :authorize
    end
  end

  namespace :admin do
    resources :shops
    resources :orders
    resources :jc_logs, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations
    resources :wechat
    resources :couriers
    resources :apis, only: [:index]
  end

  require 'dispatch'
  mount Api::Dispatch => '/api'
  mount WeixinRailsMiddleware::Engine, at: "/"

  get 'china_city/:id', to: 'city_data#show'
  get 'welcome/index'
  get 'welcome/downapp'
  get 'welcome/apply'
  post 'welcome/applied'
  post "pay_notify" => "orders#pay_notify"

  root :to => 'welcome#index'

  #match '*path', via: :all, to: 'welcome#error_404'

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :merchant
  has_many :products
  has_many :rooms
  has_many :orders
  has_many :categories
  has_many :workers
  has_many :food_materials
  has_many :comments, as: :commentable
  has_many :bookings
  has_many :coupons

  mount_uploader :avatar, ImageUploader
  attr_accessor :uploader_secure_token

  validates_uniqueness_of :name, :message => "你的店铺名称重复了"

  def update_location
    return if address == ""
    response = address_geocoding_location(address)
    location_info = JSON.parse(response.body)
    location = location_info["result"]["location"]
    update_attributes(lat: location["lat"], lng: location["lng"], location: "point(#{location["lng"]} #{location["lat"]})")
  end

  def address_geocoding_location(address)
    conn = Faraday.new(:url => "http://api.map.baidu.com") do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.response :logger                  # log requests to STDOUT
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end
    response = conn.get '/geocoder/v2/', { address: address, ak: Setting.baidu_map_ak, output: "json" }
  end

  def address
  #  "#{ChinaCity.get(province)}#{ChinaCity.get(city)}#{ChinaCity.get(district)}#{street}"
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < AdminController
  before_action :set_shop, only: [:show, :edit, :update]

  def index
    @shops = Shop.all
  end

  def show
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to admin_shops_path, :notice => "更新成功！"
    else
      render :edit, :notice => "更新失败！"
    end
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :mobile, :avatar, :address, :province, :city, :district)
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/cpanel/shops_helper.rb
module Cpanel::ShopsHelper
end

app/views/admin/shops/_form.html.erb
<%= form_for [:admin, @shop] do |f| %>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 form-control-label">店铺名称</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "名称" %>
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 form-control-label">店铺电话</label>
    <div class="col-sm-10">
      <%= f.text_field :mobile, class: "form-control", placeholder: "电话" %>
    </div>
  </div>
  <!--
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 form-control-label">店铺地区</label>
    <div class="col-sm-10">
      <div class="row">
        <div class="city-group" style="padding-top:8px;">
          <div class="col-sm-4">
            <%= f.select(:province, ChinaCity.list.collect {|p| [ p[0], p[1] ] }, { :prompt => "--省份--" }, { :class => "city-select form-control" }) %>
          </div>
          <div class="col-sm-4">
            <%= f.select(:city, ChinaCity.list(@shop.province).collect {|p| [ p[0], p[1] ] }, { :prompt => "--省份--" }, { :class => "city-select form-control" }) %>
          </div>
          <div class="col-sm-4">
            <%= f.select(:district, ChinaCity.list(@shop.city).collect {|p| [ p[0], p[1] ] }, { :prompt => "--省份--" }, { :class => "city-select form-control" }) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  -->
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 form-control-label">店铺地址</label>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control", placeholder: "地址" %>
    </div>
  </div>
  <div class="form-group row">
    <label for="inputAvatar" class="col-sm-2 form-control-label">店铺头像</label>
    <div class="col-sm-1">
      <%= image_tag(@shop.avatar.url("80x80"), :alt=>"店铺头像", :class=>"img-circle", :width => "40", :height => "40") %>
    </div>
    <div class="col-sm-9">
      <label class="file">
        <%= f.file_field :avatar %>
        <span class="file-custom"></span>
      </label>
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 form-control-label"></label>
    <div class="col-sm-10">
      <%= f.submit "保 存", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/admin/shops/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'admin/shared/left_bar' %>
    </div>
    <div class="col-sm-9">
      <div class="card card-block right-content">

        <table class="table">
          <tbody>
          <% @shops.each do |shop| %>
            <tr>
              <th scope="row">1</th>
              <td>
                <%= image_tag(shop.avatar.url("80x80"), :alt=>"店铺头像", :class=>"img-circle", :width => "40", :height => "40") %>
              </td>
              <td><%= shop.name %></td>
              <td><%= shop.mobile %></td>
              <td>
                <a href="<%= edit_admin_shop_path(shop) %>" class="btn btn-primary-outline btn-sm">修改</a>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/shops/show.html.erb
<h1>Admin::Shops#show</h1>
<p>Find me in app/views/admin/shops/show.html.erb</p>