config/routes.rb
Rails.application.routes.draw do

  resource :wechat, only: [:show, :create]
  resource :wechat, only: [:show, :create]
  resource :weixin do
    collection do
      get :authorize
    end
  end

  namespace :admin do
    resources :shops
    resources :orders
    resources :jc_logs, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations
    resources :wechat
    resources :couriers
    resources :apis, only: [:index]
  end

  require 'dispatch'
  mount Api::Dispatch => '/api'
  mount WeixinRailsMiddleware::Engine, at: "/"

  get 'china_city/:id', to: 'city_data#show'
  get 'welcome/index'
  get 'welcome/downapp'
  get 'welcome/apply'
  post 'welcome/applied'
  post "pay_notify" => "orders#pay_notify"

  root :to => 'welcome#index'

  #match '*path', via: :all, to: 'welcome#error_404'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false

  def index

  end

  def downapp

  end

  def apply

  end

  def applied
    if params[:merchant].blank? || params[:shop].blank?
      redirect_to welcome_apply_path, :alert => "资料提交失败！请正确填写下面资料！}"
    end
    merchant = Merchant.new(:mobile => params[:merchant]["mobile"],
                            :password => params[:merchant]["password"],
                            :password_confirmation => params[:merchant]["password_confirmation"])
    if not merchant.save
      redirect_to welcome_apply_path, :alert => "资料提交失败！原因：#{merchant.errors.full_messages.join(', ')}"
    end
    shop = Shop.new(:name => params[:shop][:name],
                    :merchant_id => merchant.id,
                    :mobile => params[:shop][:mobile])
    if not shop.save
      redirect_to welcome_apply_path, :alert => "资料提交失败！原因：#{shop.errors.full_messages.join(', ')}"
    end
  end

  def error_404
    render_404
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/api.html.erb
<% cache(["api", "v1"], expires_in: 1.days) do %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h4 class="panel-title">Ruby China API 目录</h4>
  </div>
  <div class="panel-body markdown">
    <h4>Response 说明</h4>
    <p>所有 Response 采用 JSON 格式返回，请求状态通过 HTTP Status 返回</p>
    <h5>HTTP Status</h5>
    <ul>
      <li>200, 201 - 请求成功，或执行成功</li>
      <li>400 - 参数不符合 API 的要求、或者数据格式验证没有通过，请配合 Response Body 里面的 error 信息确定问题。</li>
      <li>401 - 用户认证失败，或缺少认证信息，比如 access_token 过期，或没传。</li>
      <li>403 - 当前用户对资源没有操作权限</li>
      <li>404 - 资源不存在。</li>
      <li>500 - 服务器异常</li>
    </ul>
    <p>错误的情况 Response Body 一定会是这样的格式: <code>{ "error" : "Error message" }</code></p>

    <h4>API 路由</h4>

    <p>URL 基本路径：<%= request.protocol %><%= Setting.domain %>/api/v1</p>
    <div class="row">
      <div class="col-md-3">
        <ul class="route-list">
          <% @routes.each do |route| %>
          <% if route[:desc] != "" %>
          <li style="border-bottom: solid 1px #ccc;">
            <%= route[:method] %> <a href="#route-<%= route[:id] %>"><%= route[:name] %></a><br />
            <span style="color: red;"><%= markdown(route[:desc] || "暂无") %></span>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
      <div class="routes col-md-9">
        <% @routes.each do |route| %>
        <% if route[:desc] != "" %>
        <div class="route" id="route-<%= route[:id] %>">
          <h5><label><%= route[:method] %></label> <%= route[:name] %></h5>
          <div class="content">
            <div class="desc markdown"><%= markdown(route[:desc] || "暂无") %></div>
            <% if route[:params].count > 0 %>
            <h6>Params</h6>
            <table class="table table-striped table-bordered params">
              <thead>
                <th>参数名</th>
                <th>类型</th>
                <th>必填</th>
                <th>默认值</th>
                <th>值范围</th>
                <th>说明</th>
              </thead>
              <tbody>
                <% route[:params].each do |k,param| %>
                <%
                if not param.is_a?(Hash)
                  param = { type: "String", required: true, desc: "主键" }
                end
                %>
                <tr>
                  <td class="field"><%= k %></td>
                  <td class="type"><%= param[:type] %></td>
                  <td class="required"><%= param[:required] %></td>
                  <td class="default"><%= param[:default] %></td>
                  <td class="values"><%= param[:values] %></td>
                  <td><%= markdown(param[:desc] || "") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/welcome/applied.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>简餐</title>
    <%= stylesheet_link_tag    'welcome', media: 'all' %>
    <%= javascript_include_tag 'welcome' %>
    <%= csrf_meta_tags %>
    <style media="screen">
      body {
        background-color: #04BE02;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <nav class="navbar navbar-fixed-top navbar-light bg-faded">
        <div class="container">
          <a href="<%= welcome_index_path %>">
            <%= image_tag("logo.png") %>
          </a>
          <ul id="menu" class="nav navbar-nav pull-xs-right">
            <li class="nav-item small-sreen-hide active">
              <a class="nav-link hvr-underline-from-center" href="<%= welcome_index_path %>" style="color:#FFF;">首页</a>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link" style="color:#FFF;">|</span>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link">
                <a href="http://jiancan.me/cpanel.html" style="color:#FFF;" target="_blank">商家后台</a>
              </span>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container" style="padding-top:100px;">
      <div class="row card">
        <div class="col-sm-8" style="padding:50px;">
          <p>
            谢谢你的支持，资料提交成功，我们会尽快来电和你确认！请耐心等候！
          </p>
        </div>
        <div class="col-sm-1" style="text-align:center;margin-top:50px;">
          <div class="" style="margin-left:35px;width: 1px;height: 450px;background-color: #ccc;color:#FFF;">,</div>
        </div>
        <div class="col-sm-3" style="padding:50px;">
          已有简餐网商家帐号？<a href="http://jiancan.me/cpanel.html" target="_blank">立即登录</a>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/welcome/apply.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>简餐</title>
    <%= stylesheet_link_tag    'welcome', media: 'all' %>
    <%= javascript_include_tag 'welcome' %>
    <%= csrf_meta_tags %>
    <style media="screen">
      body {
        background-color: #04BE02;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <nav class="navbar navbar-fixed-top navbar-light bg-faded">
        <div class="container">
          <a href="<%= welcome_index_path %>">
            <%= image_tag("logo.png") %>
          </a>
          <ul id="menu" class="nav navbar-nav pull-xs-right">
            <li class="nav-item small-sreen-hide active">
              <a class="nav-link hvr-underline-from-center" href="<%= welcome_index_path %>" style="color:#FFF;">首页</a>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link" style="color:#FFF;">|</span>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link">
                <a href="http://jiancan.me/cpanel.html" style="color:#FFF;" target="_blank">商家后台</a>
              </span>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container" style="padding-top:100px;">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
      <div class="row card">
        <div class="col-sm-8" style="padding:50px;">
          <%= form_tag(welcome_applied_path, method: "post") do %>
            <div class="form-group row">
              <label class="col-sm-2 form-control-label">手机</label>
              <div class="col-sm-10">
                <input type="text" name="merchant[mobile]" class="form-control">
                <small class="text-muted">作为登录帐号，请填写未被简餐网商家平台注册的手机号码</small>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 form-control-label">密码</label>
              <div class="col-sm-10">
                <input type="password" name="merchant[password]" class="form-control">
                <small class="text-muted">字母、数字或者英文符号，最短6位，区分大小写</small>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 form-control-label">确认密码</label>
              <div class="col-sm-10">
                <input type="password" name="merchant[password_confirmation]" class="form-control">
                <small class="text-muted">请再次输入密码</small>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 form-control-label">店铺名称</label>
              <div class="col-sm-10">
                <input type="text" name="shop[name]" class="form-control">
                <small class="text-muted">请填写你店铺的名称，尽量和营业执照一样，用于显示在外卖平台等</small>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 form-control-label">联系电话</label>
              <div class="col-sm-10">
                <input type="text" name="shop[mobile]" class="form-control">
                <small class="text-muted">请填写你店铺的联系电话，工作人员会根据你填写的电话联系你</small>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2"></label>
              <div class="col-sm-10">
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> 我同意并遵守《简餐网平台服务协议》
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">入驻</button>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-sm-1" style="text-align:center;margin-top:50px;">
          <div class="" style="margin-left:35px;width: 1px;height: 450px;background-color: #ccc;color:#FFF;">,</div>
        </div>
        <div class="col-sm-3" style="padding:50px;">
          已有简餐网商家帐号？<a href="http://jiancan.me/cpanel.html" target="_blank">立即登录</a>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/welcome/downapp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>简餐网-下载APP</title>
    <%= stylesheet_link_tag    'weui.min', media: 'all' %>
    <%= stylesheet_link_tag    'downapp', media: 'all' %>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js" charset="utf-8"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- 20160506 add -->
    <div class="wx_mask_ios">
      <div class="wx_mask_ios_tip">
      </div>
    </div>
    <div class="wx_mask_android">
      <div class="wx_mask_ios_tip">
      </div>
    </div>
    <!-- 20160506 end -->
    <div class="weui_msg">
      <div class="weui_icon_area"><i class="weui_icon_success weui_icon_msg"></i></div>
      <div class="weui_text_area">
        <h2 class="weui_msg_title">按右上角的浏览器中打开 下载 APP</h2>
        <p class="weui_msg_desc">由于微信机制，只能用系统浏览器打开才能下载</p>
      </div>
    </div>
    <div class="weui_grids">
      <a id="c1_2_1" href="http://jiancan.me/static/jiancan.waiter.apk" class="weui_grid">
        <div class="weui_grid_icon">
          <%= image_tag('merchant-app.png') %>
        </div>
        <p class="weui_grid_label">
          商家版
        </p>
      </a>
      <a id="c1_2_2" href="javascript:;" class="weui_grid">
        <div class="weui_grid_icon">
          <%= image_tag('user-app.png') %>
        </div>
        <p class="weui_grid_label">
          用户版
        </p>
      </a>
      <a id="c1_2_3" href="javascript:;" class="weui_grid">
        <div class="weui_grid_icon">
          <%= image_tag('kitchen-app.png') %>
        </div>
        <p class="weui_grid_label">
          厨房版
        </p>
      </a>
    </div>
  </body>
  <script>
    $(document).ready(function(e) {
      // 20160506 ADD
      function isWeiXin() {
        var ua = navigator.userAgent.toLowerCase();
        if(ua.match(/MicroMessenger/i)=="micromessenger") {
          return true;
        } else {
          return false;
        }
      }

      function isIos() {
        var u = navigator.userAgent.toLowerCase();
        if (u.indexOf('iphone') > -1 || u.indexOf('ipod') > -1 ) {
          return true;
        }
        return false;
      }

      if(isWeiXin()){
        if(isIos()) {
          $("#c1_2_1").click(function(){
            $(".wx_mask_ios").show();
          });
          $("#c1_2_2").click(function(){
            $(".wx_mask_ios").show();
          });
          $("#c1_2_3").click(function(){
            $(".wx_mask_ios").show();
          });
        }else{
          $("#c1_2_1").click(function(){
            $(".wx_mask_android").show();
          });
          $("#c1_2_2").click(function(){
            $(".wx_mask_android").show();
          });
          $("#c1_2_3").click(function(){
            $(".wx_mask_android").show();
          });
        }
      }
      // 20160506 END
    });


</script>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>简餐</title>
    <%= stylesheet_link_tag    'welcome', media: 'all' %>
    <%= javascript_include_tag 'welcome' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <nav class="navbar navbar-fixed-top navbar-light bg-faded">
        <div class="container">
          <a href="<%= welcome_index_path %>">
            <%= image_tag("logo.png") %>
          </a>
          <ul id="menu" class="nav navbar-nav pull-xs-right">
            <li class="nav-item small-sreen-hide active" data-menuanchor="firstPage">
              <a class="nav-link hvr-underline-from-center" href="#firstPage" style="color:#FFF;">软件下载</a>
            </li>
            <li class="nav-item small-sreen-hide" data-menuanchor="secondPage">
              <a class="nav-link hvr-underline-from-center" href="#secondPage" style="color:#FFF;">功能简介</a>
            </li>
            <li class="nav-item small-sreen-hide" data-menuanchor="3rdPage">
              <a class="nav-link hvr-underline-from-center" href="#3rdPage" style="color:#FFF;">应用场景</a>
            </li>
            <li class="nav-item small-sreen-hide" data-menuanchor="4thpage">
              <a class="nav-link hvr-underline-from-center" href="#4thpage" style="color:#FFF;">案例分享</a>
            </li>
            <li class="nav-item small-sreen-hide" data-menuanchor="lastPage">
              <a class="nav-link hvr-underline-from-center" href="#lastPage" style="color:#FFF;">联系我们</a>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link" style="color:#FFF;">|</span>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link">
                <a href="http://jiancan.me/cpanel/index.html" style="color:#FFF;" target="_blank">商家后台</a>
              </span>
            </li>
            <li class="nav-item small-sreen-hide">
              <span class="nav-link">
                <a href="<%= welcome_apply_path %>" style="color:#FFF;">品牌入驻</a>
              </span>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div id="fullpage">
      <div class="section view-page view-page-1">
        <div class="container">
          <div class="content">
            <h1>智慧 云餐厅</h1>
            <div class="separator-container">
                <div class="separator line-separator">∎</div>
            </div>
            <h5>全面覆盖预订、排队、预点菜、外卖、堂点、快餐、支付、会员等应用场景的一体化互联网餐饮解决方案</h5>
          </div>
        </div>
      </div>
      <div class="section view-page view-page-2">
        <div class="container">
          <div class="content">
            <div class="row">
              <div class="col-sm-6">
              </div>
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-block">
                    <h2 class="card-title">简餐卖家版</h2>
                    <p class="card-text">为服务人员配备的手机点菜设备，支持点菜、取号、收银等多种功能；在配送人员的手机上安装还可以实时定位配送员地理位置。</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">官网版本：1.0  |  运行环境：android 4.4 以上、ios 8 以上</li>
                  </ul>
                  <div class="card-block">
                    <a href="#" class="card-link btn btn-primary btn-lg">
                      <i class="fa fa-android"></i> 安卓版本
                    </a>
                    <a href="#" class="card-link btn btn-primary btn-lg">
                      <i class="fa fa-apple"></i> 苹果版本
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section view-page view-page-3">
        <div class="container">
          <div class="content">
            <h1>再小的餐厅</h1>
            <h1>也有自己的品牌</h1>
            <h5>创建微信公众号和营销推广平台，积累粉丝和顾客，实现线上线下闭环</h5>
          </div>
        </div>
      </div>
      <div class="section view-page view-page-4">
        <div class="container">
          <div class="content">
            <h1>业界领先的去硬件化研发理念</h1>
            <h5>支持95%以上的餐饮收银硬件，彻底解除软件供应商对商户的硬件绑架</h5>
          </div>
        </div>
      </div>
      <div class="section view-page view-page-5">
        <div class="container">
          <div class="content">
            <div class="row">
              <div class="col-sm-6">
              </div>
              <div class="col-sm-6">
                <%= image_tag("callme.png") %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="view-page-controls">
        <ul class="list-unstyled">
          <li><i v-bind:class="[currentPageNumber == 0 ? 'fa-circle' : 'fa-circle-thin']" class="fa view-page-control"></i></li>
          <li><i v-bind:class="[currentPageNumber == 1 ? 'fa-circle' : 'fa-circle-thin']" class="fa view-page-control"></i></li>
          <li><i v-bind:class="[currentPageNumber == 2 ? 'fa-circle' : 'fa-circle-thin']" class="fa view-page-control"></i></li>
          <li><i v-bind:class="[currentPageNumber == 3 ? 'fa-circle' : 'fa-circle-thin']" class="fa view-page-control"></i></li>
          <li><i v-bind:class="[currentPageNumber == 4 ? 'fa-circle' : 'fa-circle-thin']" class="fa view-page-control"></i></li>
        </ul>
      </div>
    </div>

    <footer class="bd-footer text-muted navbar-fixed-bottom">
      <div class="container" style="text-align:center;font-size:13px;color:#FFF;">
        <p>
          Copyright 2013 &copy; - <a href="#" style="color:#FFF;">动起来软件公司</a> - <a style="color:#FFF;" href="http://www.miibeian.gov.cn/">粤ICP备15005696号-3</a>
        </p>
      </div>
    </footer>
  </body>
</html>