config/routes.rb
Rails.application.routes.draw do

  resource :wechat, only: [:show, :create]
  resource :wechat, only: [:show, :create]
  resource :weixin do
    collection do
      get :authorize
    end
  end

  namespace :admin do
    resources :shops
    resources :orders
    resources :jc_logs, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations
    resources :wechat
    resources :couriers
    resources :apis, only: [:index]
  end

  require 'dispatch'
  mount Api::Dispatch => '/api'
  mount WeixinRailsMiddleware::Engine, at: "/"

  get 'china_city/:id', to: 'city_data#show'
  get 'welcome/index'
  get 'welcome/downapp'
  get 'welcome/apply'
  post 'welcome/applied'
  post "pay_notify" => "orders#pay_notify"

  root :to => 'welcome#index'

  #match '*path', via: :all, to: 'welcome#error_404'

end

app/models/courier.rb
class Courier < ApplicationRecord
  has_secure_password

  validates :name, :login, presence: true
  validates :login, uniqueness: true

  has_many :orders

  def pusher_id
    "courier_#{id}"
  end

  # 重新生成 Private Token
  def update_private_token
    random_key = "#{SecureRandom.hex(10)}:#{id}"
    update_attributes(:private_token => random_key, :private_token_updated_at => Time.zone.now)
  end

  after_create :ensure_private_token!
  def ensure_private_token!
    update_private_token
  end

  def get_private_token
    ensure_private_token!
    private_token
  end

  def check_token_updated
    private_token_updated_at > Time.zone.now - 7.days
  end
end

app/controllers/admin/couriers_controller.rb
class Admin::CouriersController < AdminController

  before_action :set_courier, only: [:show, :edit, :update, :destroy]

  def index
    @couriers = Courier.all
  end

  def show

  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)
    if @courier.save
      redirect_to admin_couriers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @courier.update courier_params
      redirect_to :admin_couriers_path
    else
      render :edit
    end
  end

  def destroy
    if @courier.destroy
      redirect_to :admin_couriers_path
    else
      redirect_to :admin_couriers_path
    end
  end

  private
  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :login, :mobile, :password, :password_confirmation)
  end
end

app/views/admin/couriers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'admin/shared/left_bar' %>
    </div>
    <div class="col-sm-9">
      <div class="card card-block right-content">
        <div class="navbar navbar-light bg-faded navigation">
          <a href="<%= admin_couriers_path %>" class="nav-link btn btn-primary-outline btn-sm">
            <i class="fa fa-arrow-left"></i> 返回
          </a>
          <span class="title">添加快递员</span>
        </div>
        <%= form_for [:admin, @courier] do |f| %>
          <div class="form-group">
            <label for="exampleInputEmail1">名称</label>
            <%= f.text_field :name, class: "form-control", placeholder: "名称" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">登录名</label>
            <%= f.text_field :login, class: "form-control", placeholder: "登录名" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">电话</label>
            <%= f.text_field :mobile, class: "form-control", placeholder: "电话" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">确认密码</label>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "确认密码" %>
          </div>
          <%= f.submit "保 存", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/couriers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'admin/shared/left_bar' %>
    </div>
    <div class="col-sm-9">
      <div class="card card-block right-content">
        <div class="navbar navbar-light bg-faded navigation">
          <a class="nav-link btn btn-primary-outline btn-sm">
            <i class="fa fa-arrow-left"></i> 返回
          </a>
          <span class="title">快递员管理</span>
          <a href="<%= new_admin_courier_path %>" class="nav-link btn btn-primary-outline btn-sm pull-xs-right">
            <i class="fa fa-plus"></i> 添加
          </a>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>编号</th>
              <th>名称</th>
              <th>登录名</th>
              <th>电话</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
          <% @couriers.each do |courier| %>
            <tr>
              <td><%= courier.id %></td>
              <td>
                <%= courier.name %>
              </td>
              <td>
                <%= courier.login %>
              </td>
              <td>
                <%= courier.mobile %>
              </td>
              <td>
                <%= link_to "修改", edit_admin_courier_path(courier) %>
                <%= link_to "删除", admin_courier_path(courier), method: :delete %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/couriers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'admin/shared/left_bar' %>
    </div>
    <div class="col-sm-9">
      <div class="card card-block right-content">
        <div class="navbar navbar-light bg-faded navigation">
          <a href="<%= admin_couriers_path %>" class="nav-link btn btn-primary-outline btn-sm">
            <i class="fa fa-arrow-left"></i> 返回
          </a>
          <span class="title">添加快递员</span>
        </div>
        <%= form_for [:admin, @courier] do |f| %>
          <div class="form-group">
            <label for="exampleInputEmail1">名称</label>
            <%= f.text_field :name, class: "form-control", placeholder: "名称" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">登录名</label>
            <%= f.text_field :login, class: "form-control", placeholder: "登录名" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">电话</label>
            <%= f.text_field :mobile, class: "form-control", placeholder: "电话" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">确认密码</label>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "确认密码" %>
          </div>
          <%= f.submit "保 存", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>