config/routes.rb
Rails.application.routes.draw do

  resource :wechat, only: [:show, :create]
  resource :wechat, only: [:show, :create]
  resource :weixin do
    collection do
      get :authorize
    end
  end

  namespace :admin do
    resources :shops
    resources :orders
    resources :jc_logs, only: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy]
    resources :registrations
    resources :wechat
    resources :couriers
    resources :apis, only: [:index]
  end

  require 'dispatch'
  mount Api::Dispatch => '/api'
  mount WeixinRailsMiddleware::Engine, at: "/"

  get 'china_city/:id', to: 'city_data#show'
  get 'welcome/index'
  get 'welcome/downapp'
  get 'welcome/apply'
  post 'welcome/applied'
  post "pay_notify" => "orders#pay_notify"

  root :to => 'welcome#index'

  #match '*path', via: :all, to: 'welcome#error_404'

end

app/views/admin/shared/_left_bar.html.erb
<div class="sidebar">
  <div class="list-group">
    <a href="<%= admin_shops_path %>" class="list-group-item <%= active_controller?("shops") %>">
      店铺管理
    </a>
    <a href="<%= admin_orders_path %>" class="list-group-item <%= active_controller?("orders") %>">订单管理</a>
    <a href="<%= admin_couriers_path %>" class="list-group-item <%= active_controller?("couriers") %>">快递员管理</a>
    <a href="<%= admin_jc_logs_path %>" class="list-group-item <%= active_controller?("jc_logs") %>">日志管理</a>
    <a href="<%= admin_apis_path %>" class="list-group-item <%= active_controller?("apis") %>">API文档</a>
  </div>
</div>